replicaCount: 1

image:
  repository: eyalpoly/authorization-manager
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

env:
  - name: NODE_ENV
    value: "DEV"
  - name: GOOGLE_CLOUD_PROJECT_ID
    value: "attendme-32125"
  - name: JWT_SECRET_NAME_POSTFIX
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: secretNamePostfix
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "{{ .Values.gcpCreds.mountPath }}/gcp-service-account.json"
  - name: LOG_LEVEL
    value: "info"

gcpCreds:
  mountPath: /var/secrets/google
  secretName: gcp-creds-secret

jwtSecretName: jwt-secret
jwtSecretKey: secretNamePostfix