apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authorization-manager.fullname" . }}
  labels:
    {{- include "authorization-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authorization-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authorization-manager.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
      volumes:
        - name: gcp-creds
          secret:
            secretName: {{ .Values.gcpCreds.secretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
{{- with .Values.env }}
{{ toYaml . | indent 12 }}
{{- end }}

          volumeMounts:
            - name: gcp-creds
              mountPath: {{ .Values.gcpCreds.mountPath }}
              readOnly: true
          resources:
{{- toYaml .Values.resources | indent 12 }}