name: Release Charts

on:
  push:
    branches:
      - main
        # Exclude version bump commits from triggering the workflow
        # Add condition based on commit message
        # Use a regular expression to exclude commit messages with the pattern "chore: bump chart version"
        # from triggering the workflow
        if: "!contains(github.event.head_commit.message, 'chore: bump chart version')"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # Check if commit message contains "chore: bump chart version"
      - name: Check if commit message is version bump
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"chore: bump chart version"* ]]; then
            echo "This is a version bump commit, skipping chart release."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "This is not a version bump commit, continuing with the release."
            echo "skip=false" >> $GITHUB_ENV
          fi

      # Bump Chart Versions
      - name: Bump chart version (patch)
        run: |
          for chart in charts/*; do
            chart_yaml="$chart/Chart.yaml"
            if [ -f "$chart_yaml" ]; then
              echo "Bumping version in $chart_yaml"
              version=$(grep '^version:' "$chart_yaml" | awk '{print $2}')
              IFS='.' read -r major minor patch <<< "$version"
              new_version="$major.$minor.$((patch + 1))"
              sed -i "s/^version: .*/version: $new_version/" "$chart_yaml"
              echo "New version: $new_version"
            fi
          done

      # Commit and push version bump
      - name: Commit and push chart version bump
        run: |
          git add charts/*/Chart.yaml
          git commit -m "chore: bump chart version [automated]"
          git push

      # Debug step to check chart directory structure
      - name: Debug chart directory
        run: |
          echo "Chart directory contents:"
          ls -la charts/
          echo "Chart structure:"
          find charts -type f | sort

      # Package charts manually to verify they're valid
      - name: Package charts manually
        run: |
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d .cr-release-packages/
            fi
          done
          ls -la .cr-release-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"

      # Verify gh-pages branch content
      - name: Verify gh-pages content
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "gh-pages branch contents:"
          ls -la
          echo "index.yaml content:"
          cat index.yaml